### PR TITLE
Update to Material 3

### PR DESCRIPTION
**Pull request by santoni0**
Required for [Szkolny.eu](https://github.com/szkolny-eu/szkolny-android) migration to Material 3

### CODE REVIEW

**Comment by kuba2k2** [comment]
Cool! Let me know when you mark it as ready-to-review, in case I don't get a notification.

**Comment by kuba2k2** [comment]
Also, keep in mind that it would be best if existing themes in Szkolny.eu would keep working. Maybe not all of them are state-of-the-art, but I like that you can at least personalize the colors, especially if your phone is pre-Android 12.

**Comment by santoni0** [comment]
> Also, keep in mind that it would be best if existing themes in Szkolny.eu would keep working. Maybe not all of them are state-of-the-art, but I like that you can at least personalize the colors, especially if your phone is pre-Android 12.

They're still working right now, and I'll leave them as they were.

**Comment by santoni0** [comment]
Newest [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) releases come with the requirement of app minSdk 21, are you ok with updating it?

**Comment by kuba2k2** [comment]
Not really. They say it works down to API 16, are you sure it's 21? Also, I'm not sure if we want to use alphas or betas of MaterialDrawer, as they may be pretty unstable still, especially with the amount of changes that M3 introduces.

**Comment by santoni0** [comment]
I'm sure. Their readme must be outdated (for example it still states that it supports Material 2). Here's the screenshot of the library build.gradle file.
Screenshot_20221018-103840
Also, I think that 9.0.1 is just a normal release. (betas were named like v9.0.0-b01)

**Comment by kuba2k2** [comment]
Would simply decreasing the minSdk work?

**Comment by santoni0** [comment]
No, Navlib was getting an build error when it was below 21

**Comment by kuba2k2** [comment]
Well, I just changed the minSdk of MaterialDrawer to 16, and deployed it to a device running 19 (4.4.4). It runs with no problems, except that all the text is red for some reason. 

MD includes AboutLibraries for some reason (what if a project doesn't use it at all?). One of the versions working on API 16 is 8.9.4, so that would need to be changed as well.

**Comment by santoni0** [comment]
You did this on the newest MaterialDrawer? Here's the error that I've got:

**Comment by kuba2k2** [comment]
Yes, newest version. I said that I *changed* the minSdk - meaning that I modified their build.gradle, and then compiled it. Because I got no runtime errors (so far), I think you can safely add that `tools:overrideLibrary` that Gradle suggests. Also, you might need to exclude MD's AboutLibraries 10.x dependency, and use the older version that Szkolny.eu uses. (unless AboutLibraries 10.x also works on API <21, which I didn't test).

**Comment by santoni0** [comment]
I've closed the PR in order to make it count in Hacktoberfest (mustn't be a draft). But I'm still continuing work on it and i'll reopen it in 7 days.

**Comment by santoni0** [comment]
Also, is this okay for you if I create a work-in-progress PR in Szkolny.eu repo with my ongoing changes?

**Comment by santoni0** [comment]
I've made this PR ready to review just to make it count in Hacktoberfest, I'm still working on it. Also, is this okay for you if I create a work-in-progress PR in Szkolny.eu repo with my ongoing changes?

**Comment by kuba2k2** [comment]
Haha, sure, go for it. Personally I think that draft PRs should also be acceptable, especially if they have a lot of changes like this one.

**Pull request closed without merging**
